### PR TITLE
Get rid of interface parameter in public flow functions

### PR DESCRIPTION
**Pull request by mbulatova**
Created a bunch of functions instead:
SetReceiver -> SetReceiver, SetReceiverKNI, SetReceiverFile
SetSender -> SetSender, SetSenderKNI, SetSenderFile
SetHandler -> SetHandler, SetHandlerDrop, SetVectorHandler,
SetVectorHandlerDrop
SetGenerator-> SetGenerator, SetFastGenerator, SetVectorFastGenerator
SetSeparator -> SetSeparator, SetVectorSeparator

### CODE REVIEW

**Comment by ifilippov** [comment]
Firstly remove SendKNIParameters, SendKNI, ReceiveKNI etc. they are not required -> previous implementation inside one function is OK for now.

**Comment by dkolistratova** [comment]
Are u sure that changed everything? Readme at least. 
The last time I changed flow.go I had to change ~50-60 files, here 22 changed, suspicious.

**Comment by mbulatova** [comment]
@dkolistratova, changes are not so large here (only Generators, some Handler usages and kni.go are affected)

**Comment by mbulatova** [comment]
@ifilippov, corrected.

**Comment by ifilippov** [comment]
Maybe I missed something, however approved, please merge.

@gshimansky you should update tutorial presentation according to this changes.

**Pull request merged**
